config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :ticket_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # User Actions
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  namespace :admin do
    resources :users, only: [ :destroy, :edit, :update ]
  end

  # Pages Actions
  get "/home", to: "pages#home"

  # Admin Actions
  get "/admin/index", to: "admin_session#index"
  get "/admin/new", to: "admin_session#new" # Admin 'Login'
  post "/admin/create", to: "admin_session#create" # Admin Login Action

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/controllers/ticket_types_controller.rb
class TicketTypesController < ApplicationController
  before_action :admin_check, only: %i[ show edit create destory update ]
  before_action :set_ticket_type, only: %i[ show edit update ]

  def show
  end

  def new
    @ticket_type = TicketType.new
  end

  def create
    @ticket_type = TicketType.new(ticket_type_params)

    respond_to do |format|
      if @ticket_type.save
        format.html { redirect_to admin_index_path, notice: "Ticket Type Was Created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # This actually will not 'destory' a ticket type. But it will disable it.
  def destory
  end

  def edit
    unless current_user.is_admin?
      head :forbidden
    end
  end

  def update
    unless current_user.is_admin?
      head :forbidden
    end

    respond_to do |format|
      if @ticket_type.update(ticket_type_params)
        format.html { redirect_to @ticket_type, notice: "Ticket Type was saved." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private
  def ticket_type_params
    params.expect(ticket_type: [ :type_name ])
  end

  def set_ticket_type
    @ticket_type = TicketType.find(params.expect(:id))
  end

  def admin_check
    return unless current_user.is_admin?

    flash[:notice] = "Unexplained error occured."

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/ticket_type_helper.rb
module TicketTypeHelper
end

app/views/ticket_types/_form.html.erb
<%= form_with(model: ticket_type) do |form| %>
    <% if ticket_type.errors.any? %>
        <div style="color: red;">
            <h2><%= pluralize(ticket_type.errors.count, "Error") %> prohibited saving the Ticket Type.</h2>
        
        <ul>
            <% ticket_type.errors.each do |error| %>
                <li><%= error.full_message %></li>
            <% end %>
        </ul>

        </div>
    <% end %>

    <div class="row align-items-start p-4 border">
        <div class="col p-1">
            <div class="float-start me-1">
                <%= form.label :type_name %>
            </div>
            <div class="float-start me-1">
                <%= form.text_field :type_name, class: "form-control" %>
            </div>
        </div>
    </div>
    <div class="row align-items-start p-4">
        <div class="col">
            <%= form.submit(class: "btn btn-primary") %>
        </div>
    </div>
<% end %>

app/views/ticket_types/_type.html.erb
<div class="row">
    <div class="col">
        <div class="float-start me-1">
            <label for="ticket_type_name">Type Name</label>
        </div>
        <div class="float-start me-1">
            <input id="ticket_type_name" class="form-control w32" value="<%= @ticket_type.type_name %>" disabled>
        </div>
    </div>
</div>

app/views/ticket_types/edit.html.erb
<%= render "form", ticket_type: @ticket_type %>

app/views/ticket_types/new.html.erb
<h1>New Ticket</h1>

<%= render "form", ticket_type: @ticket_type %>

app/views/ticket_types/show.html.erb
<div class="row mb-4">
    <div class="col">
        <h1>Ticket Type</h1>
    </div>
</div>

<%= render "type" %>

<div class="row mt-4">
    <div class="col">
        <%= link_to "Edit this ticket", edit_ticket_type_path(@ticket_type), class:"btn btn-primary" %>
    </div>
    <div class="col">
    </div>
    <div class="col">
    </div>
</div>