config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :ticket_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # User Actions
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  namespace :admin do
    resources :users, only: [ :destroy, :edit, :update ]
  end

  # Pages Actions
  get "/home", to: "pages#home"

  # Admin Actions
  get "/admin/index", to: "admin_session#index"
  get "/admin/new", to: "admin_session#new" # Admin 'Login'
  post "/admin/create", to: "admin_session#create" # Admin Login Action

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/pages/_ticket-list.html.erb
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Ticket Number</th>
      <th>Ticket Type</th>
      <th>Ticket Title</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.id %></td>
      <td><%= @ticket_types_hash[ticket.ticket_type_id] || "Unknown Type" %></td>
      <td><%= ticket.title %></td>
      <td>
        <%= link_to "Show this Ticket", ticket, class: "btn btn-primary float-start me-2"%>
        <%= button_to "Delete ticket", ticket, method: :delete, class: "btn btn-danger float-start" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/_ticket-type-list.html.erb
<h3>Current Tickets Types</h3>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Type name</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @ticket_types.each do |type| %>
    <tr>
      <td><%= type.type_name %></td>
      <td>
        <% if current_user.is_admin? %>
          <%= link_to "View Ticket Type", type, class: "btn btn-primary float-start me-2" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div class="col">
    <%= link_to "New Ticket Type", new_ticket_type_path, class:"btn btn-primary" %>
  </div>
</div>

app/views/pages/_user-list.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>User Email</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <%= link_to "Edit User", edit_admin_user_path(user), class: "btn btn-primary float-start me-2" %>
        <% if user.enabled %>
          <%= link_to "Destory User", admin_user_path(user), data: { "turbo-method": :delete }, class: "btn btn-danger float-start" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="row">
  <div class="col">
    <%= link_to "Add User", new_user_registration_path, class: "btn btn-primary" %>
  </div>
</div>