config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :ticket_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # User Actions
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  namespace :admin do
    resources :users, only: [ :destroy, :edit, :update ]
  end

  # Pages Actions
  get "/home", to: "pages#home"

  # Admin Actions
  get "/admin/index", to: "admin_session#index"
  get "/admin/new", to: "admin_session#new" # Admin 'Login'
  post "/admin/create", to: "admin_session#create" # Admin Login Action

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :title, presence: true
  belongs_to :ticket_type, required: true
end

app/models/ticket_type.rb
class TicketType < ApplicationRecord
  has_many :ticket
  validates :type_name, presence: true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]
  before_action :ticket_types_ary, only: %i[ index new edit create update ]
  before_action :ticket_types_hash, only: %i[ show ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy!

    respond_to do |format|
      format.html { redirect_to tickets_path, status: :see_other, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callback here to get ticket types to prevent DRY.
    def ticket_types_ary
      @ticket_type = TicketType.order(:type_name)
    end

    def ticket_types_hash
      @ticket_type_hash = TicketType.order(:type_name).map { |type| [ type.id, type.type_name ] }.to_h
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.expect(ticket: [ :title, :ticket_type_id, :body ])
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row align-items-start p-4 border">
      <div class="col p-1">
        <div class="float-start me-1">
          <%= form.label :title %>
        </div>
        <div class="float-start w-75">
          <%= form.text_field :title, class:"form-control" %>
        </div>
      </div>
      <div class="col p-1">
        <div class="float-start me-1">
          <%= form.label :ticket_type_id %>
        </div>
        <div class="float-start w-75">
          <%= form.collection_select(:ticket_type_id, TicketType.all, :id, :type_name, { prompt: true}, { class: "form-control" }) %>
        </div>
      </div>
    </div>
    <div class="row p-4 border">
      <div class="col p-1">
        <%= form.label :body %>
        <%= form.textarea :body, class: "form-control", rows: "8" %>
      </div>
    </div>
    <div class="row p-4">
      <%= form.submit(class: "btn btn-primary", style: "width: 150px") %>
    </div>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
  <div class="container">
    <div class="row align-items-start p-4 border">
      <div class="col p-1">
        <div class="float-start me-1">
          <strong>Title:</strong>
        </div>
        <div class="float-start w-75">
          <input type="text" class="form-control" value="<%= ticket.title %>" disabled>
        </div>
      </div>
      <div class="col p-1">
        <div class="float-start me-1">
          <strong>Type</strong>
        </div>
        <div class="float-start w-75">
          <select class="form-control" disabled>
            <option><%= @ticket_type_hash[@ticket.ticket_type_id] || "Unknown Type" %></option>
          </select>
        </div>
      </div>
    </div>
    <div class="row p-4 border">
      <div class="col p-1">
        <strong>Body</strong>
<textarea class="form-control" rows="8" disabled>
<%= ticket.body %>
</textarea>
      </div>
    </div>
  </div>
</div>

app/views/tickets/edit.html.erb
<% content_for :title, "Editing ticket" %>

<h1>Editing ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<%= link_to "New ticket", new_ticket_path, class:"btn btn-primary"%>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.ticket_type_id %></td>
        <td><%= link_to "Show this Ticket", ticket %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/new.html.erb
<% content_for :title, "New ticket" %>

<div class="text-center mb-4">
  <h1>New ticket</h1>
</div>

<%= render "form", ticket: @ticket %>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div class="container p-4">
  <div class="float-start me-2">
    <%= link_to "Edit this ticket", edit_ticket_path(@ticket), class:"btn btn-primary" %>
  </div>
  <div class="float-start me-2">
    <%= link_to "Back to tickets", tickets_path, class: "btn btn-secondary" %>
  </div>
  <div class="float-start">
    <%= button_to "Destroy this ticket", @ticket, method: :delete, class: "btn btn-danger" %>
  </div>
</div>