config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :ticket_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # User Actions
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  namespace :admin do
    resources :users, only: [ :destroy, :edit, :update ]
  end

  # Pages Actions
  get "/home", to: "pages#home"

  # Admin Actions
  get "/admin/index", to: "admin_session#index"
  get "/admin/new", to: "admin_session#new" # Admin 'Login'
  post "/admin/create", to: "admin_session#create" # Admin Login Action

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="mx-auto" style="min-width: fit-content">
      <div class="row text-center">
        <a class="navbar-brand mx-auto" href="#">Ticket Manager</a>
      </div>
      <div class="row justify-content-center">
        <ul class="navbar-nav mb-2 ps-4">
          <li class="nav-item me-1">
            <a class="nav-link active" aria-current="page" href="/home">Home</a>
          </li>
          <li class="nav-item me-1">
            <a class="nav-link active" aria-current="page" href="/home">Profile</a>
          </li>
          <li class="nav-item dropdown me-1">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Tickets
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/tickets">View Tickets</a></li>
              <li><a class="dropdown-item" href="/tickets/new">Create New Ticket</a></li>
            </ul>
          </li>
          <li class="nav-item me-1">
            <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: "btn btn-danger" %>
          </li>
          <% if current_user.is_admin? %>
          <li class="nav-item me-1">
            <%= link_to "Admin Portal", admin_new_path, class: "btn btn-primary" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ticket Manager" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <!-- TODO: Figure out a better way to do this shit. margin-top is a 'okay' solution but not really -->
    <div class="container p-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= content_for(:title) || "Ticket Manager" %></title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="mobile-web-app-capable" content="yes">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= javascript_importmap_tags %>
        <%= yield :head %>


        <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
        <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

        <link rel="icon" href="/icon.png" type="image/png">
        <link rel="icon" href="/icon.svg" type="image/svg+xml">
        <link rel="apple-touch-icon" href="/icon.png">

        <%# Includes all stylesheet files in app/assets/stylesheets %>
        <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    </head>
    <body class="container-fluid">
        <%= yield %>
    </body>
</html>